"use client";
/* eslint-disable @next/next/no-img-element -- object URLs are local, transient previews */
import { FormEvent, useMemo, useState } from "react";
import targets from "@/data/ireland-targets-2026-08-02.json";
import retail from "@/data/ireland-retail-2026-08-02.json";
import hunts from "@/data/hunt-map-2026.json";

type Result = { traceId: string; cars: Array<{ rank:number; observationId:string; identification:{casting:string;brand:string;releaseYear:number|null;line:string;chaseStatus:string;confidence:string}; score:{total:number;tier:string;components:Record<string,number>}; marketEvidenceGrade:string; condition:{grade:string}; recommendation:{decision:string;packaging:string;conditionGate:{status:string;label:string}}; priceGate:{verdict:string;note:string}; verificationNeeded:string[] }>; scene:{caseOrMixInference:string|null;inferenceEvidence:string[]}; proactiveTargets:Array<{name:string;reason:string;visualMarkers:string[];confidence:string}>; limitations:string[] };

export default function Home() {
  const [files,setFiles]=useState<File[]>([]),[price,setPrice]=useState(""),[market,setMarket]=useState("IE"),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState<"analyze"|"targets"|"market">("analyze");
  const previews=useMemo(()=>files.map((file)=>({file,url:URL.createObjectURL(file)})),[files]);
  async function submit(event:FormEvent){event.preventDefault();if(!files.length)return;setBusy(true);setError("");setResult(null);const form=new FormData();files.forEach((file)=>form.append("images",file));form.set("market",market);if(price)form.set("observedPrice",price);form.set("currency",market==="IE"?"EUR":"USD");try{const response=await fetch("/api/analyze",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error??"Analysis failed");setResult(body);}catch(cause){setError(cause instanceof Error?cause.message:"Analysis failed");}finally{setBusy(false);}}
  return <main>
    <nav><a className="brand" href="#top"><span>DV</span> Frontier Intelligence</a><div className="navlinks"><button onClick={()=>setTab("analyze")} className={tab==="analyze"?"active":""}>Analyst</button><button onClick={()=>setTab("targets")} className={tab==="targets"?"active":""}>Targets</button><button onClick={()=>setTab("market")} className={tab==="market"?"active":""}>Ireland</button></div><a className="site-link" href="https://dalyventures.com/" target="_blank">Daly Ventures ↗</a></nav>
    <header id="top"><div><p className="eyebrow">MULTIMODAL COLLECTOR INTELLIGENCE · MODEL V2.0</p><h1>See the car.<br/><em>Know the move.</em></h1><p className="lede">Exact-release analysis, transparent scoring, price discipline and proactive hunt targets—built for every peg wall, case and collection decision.</p></div><div className="signal"><span>LIVE MODEL</span><strong>4</strong><p>separate decision gates</p><small>Priority · Evidence · Condition · Price</small></div></header>

    {tab==="analyze"&&<><section className="workbench"><div className="section-head"><div><p className="eyebrow">01 · ANALYZE</p><h2>Upload the evidence</h2></div><p>Use a full card front, back, chase-marker close-up, or a peg-wall photo. Up to four images.</p></div><form onSubmit={submit}><label className="drop"><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(e)=>setFiles(Array.from(e.target.files??[]).slice(0,4))}/>{previews.length?<div className="previews">{previews.map(({file,url})=><img key={file.name} src={url} alt="Selected Hot Wheels evidence"/>)}</div>:<><b>Drop car photos here</b><span>JPEG, PNG or WebP · 10 MB each</span></>}</label><div className="controls"><label>Buyer market<select value={market} onChange={(e)=>setMarket(e.target.value)}><option value="IE">Ireland · EUR</option><option value="US">United States · USD</option></select></label><label>Shelf price <input inputMode="decimal" placeholder="Optional" value={price} onChange={(e)=>setPrice(e.target.value)}/></label><button className="primary" disabled={busy||!files.length}>{busy?"Running evidence pipeline…":"Analyze & rank"}</button></div></form>{error&&<p className="error">{error}</p>}</section>
    {!result&&<section className="method-grid"><article><span>01</span><h3>Identify</h3><p>Exact casting, release, line, livery and visible chase markers—with confidence.</p></article><article><span>02</span><h3>Score</h3><p>Seven bounded components totaled deterministically in application code.</p></article><article><span>03</span><h3>Gate</h3><p>Market evidence, condition and regional price remain separate from taste.</p></article><article><span>04</span><h3>Hunt</h3><p>Nearby cars become case intelligence and proactive search targets.</p></article></section>}
    {result&&<section className="results"><div className="section-head"><div><p className="eyebrow">02 · RANKED RESULT</p><h2>{result.cars.length} visible {result.cars.length===1?"car":"cars"}</h2></div>{result.scene.caseOrMixInference&&<div className="case-call"><span>CASE SIGNAL</span><b>{result.scene.caseOrMixInference}</b></div>}</div>{result.cars.map((car)=><article className="car" key={car.observationId}><div className="rank">#{car.rank}</div><div className="score"><strong>{car.score.total}</strong><span>{car.score.tier}</span></div><div className="car-main"><p className="eyebrow">{car.identification.confidence} confidence · {car.identification.chaseStatus.replaceAll("_"," ")}</p><h3>{car.identification.casting}</h3><p>{car.identification.releaseYear??"Year unresolved"} · {car.identification.line}</p><div className="badges"><span>{car.recommendation.decision}</span><span>Evidence {car.marketEvidenceGrade}</span><span className={car.recommendation.conditionGate.status}>{car.condition.grade} condition</span><span className={car.priceGate.verdict}>{car.priceGate.verdict.replaceAll("_"," ")}</span></div><p className="verdict"><b>{car.recommendation.packaging}.</b> {car.priceGate.note}</p>{car.verificationNeeded.length>0&&<details><summary>Verification queue · {car.verificationNeeded.length}</summary><ul>{car.verificationNeeded.map((v)=><li key={v}>{v}</li>)}</ul></details>}</div></article>)}
      {result.proactiveTargets.length>0&&<div className="hunt-box"><p className="eyebrow">PROACTIVE HUNT</p><h2>Search the pegs for</h2><div className="target-grid">{result.proactiveTargets.map((t)=><article key={t.name}><b>{t.name}</b><p>{t.reason}</p><small>{t.visualMarkers.join(" · ")}</small></article>)}</div></div>}<p className="trace">Trace {result.traceId}</p></section>}</>}

    {tab==="targets"&&<section className="data-section"><div className="section-head"><div><p className="eyebrow">IRELAND · 02 AUG 2026</p><h2>Priority target board</h2></div><p>Exact releases worth paying Irish retail for. Re-verify stock and duplicates.</p></div><div className="target-table"><div className="table-row header"><span>Rank</span><span>Target</span><span>Score</span><span>Price</span><span>Move</span></div>{targets.targets.map((t)=><div className="table-row" key={t.rank}><span>#{t.rank}</span><b>{t.name}<small>{t.category}</small></b><span className="mini-score">{t.score} · {t.tier}</span><span>€{t.price}</span><span>{t.decision}</span></div>)}</div><div className="hunt-strip">{hunts.cases.map((c)=><div key={c.case}><b>{c.case}</b><span>{c.super}</span><small>{c.treasure}</small></div>)}</div></section>}
    {tab==="market"&&<section className="data-section"><div className="section-head"><div><p className="eyebrow">REGIONAL PRICE INTELLIGENCE</p><h2>Ireland retail gates</h2></div><p>Snapshot {retail.asOf}. Prices age; the provenance date never disappears.</p></div><div className="price-grid">{retail.benchmarks.map((r)=><article key={r.category}><small>{r.category.replaceAll("_"," ")}</small><strong>€{r.normalPrice}</strong><p>{r.retailer}</p><span>Strong ≤ €{r.strongBuyAtOrBelow}</span></article>)}</div><div className="notes">{retail.notes.map((n)=><p key={n}>↳ {n}</p>)}</div></section>}
    <footer><div><b>Hot Wheels Frontier Analyst</b><p>Collection intelligence, not a return forecast. Exact releases and high-value claims require verification.</p></div><div><a href="https://orangetrackdiecast.com/hot-wheels-casting-database/" target="_blank">Orange Track Database ↗</a><a href="https://www.hwtreasure.com/" target="_blank">HWtreasure ↗</a></div><small>Independent project · Not affiliated with Mattel</small></footer>
  </main>;
}
